language: node_js
node_js:
  - "6"
  - "8"
  - "10"
install: "true"
before_script:
  - tmp=$(mktemp --directory)
  - bash -O dotglob -O extglob -c 'mv !(test.js) "$1"/' bash "$tmp"
  - pack=$(npm pack "$tmp")
  - tar --strip-components=1 -x -v -f "$pack"
